// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateDatabaseAndUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GenerateRandomPassword(arg1:number):Promise<string>;

export function LoadServers():Promise<Record<string, string>>;

export function SelectTheme(arg1:string):Promise<void>;
