// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateDatabaseAndUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDatabaseAndUser'](arg1, arg2, arg3, arg4);
}

export function GenerateRandomPassword(arg1) {
  return window['go']['main']['App']['GenerateRandomPassword'](arg1);
}

export function LoadServers() {
  return window['go']['main']['App']['LoadServers']();
}

export function SelectTheme(arg1) {
  return window['go']['main']['App']['SelectTheme'](arg1);
}
